# Generated by Django 5.1.7 on 2025-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='offline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_in_voice', models.TextField()),
                ('channel_name', models.CharField(max_length=100)),
                ('total_count', models.BigIntegerField()),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
