# Generated by Django 5.1.7 on 2025-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicestatus',
            name='total_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
