# Generated by Django 5.1.7 on 2025-04-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='join_date',
        ),
    ]
